// OTOMATİK ÜRETİLDİ – tools/generate_widget_verses.py
// Kaynak: assets/database/quran.db (Türkçe meal)

struct WidgetVerseData {
    static let all: [(ref: String, text: String)] = [
        ("Bakara 2:40", "Ey İsrailoğulları! Size verdiğim nimeti hatırlayın ve ahdimi yerine getirin ki Ben de yerine getireyim; yoksa benden korkun."),
        ("Bakara 2:43", "Namazı kılın, zekatı verin, rüku edenlerle birlikte rüku edin."),
        ("Bakara 2:47", "Ey İsrailoğulları! Size verdiğim nimeti ve sizi bir zamanlar alemlere üstün kıldığımı hatırlayın."),
        ("Bakara 2:82", "İnanıp yararlı işler yapan kimseler cennetlik olanlardır, onlar da orada temellidirler."),
        ("Bakara 2:107", "Göklerin ve yerin Hükümdarlığının Allah'a aid olduğunu bilmez misin? Allah'tan başka dost ve yardımcınız yoktur."),
        ("Bakara 2:122", "Ey İsrailoğulları! Size verdiğim nimeti ve sizi bir zamanlar alemlere üstün tuttuğumu hatırlayın."),
        ("Bakara 2:152", "Artık Beni anın, Ben de sizi anayım; Bana şükredin, nankörlük etmeyin."),
        ("Bakara 2:153", "Ey İnananlar! Sabır ve namazla yardım dileyin. Allah, muhakkak ki sabredenlerle beraberdir."),
        ("Bakara 2:155", "Muhakkak sizi biraz korku, biraz açlık ve mallardan, canlardan, ürünlerden biraz eksiltmekle deneriz, sabredenleri müjdele."),
        ("Bakara 2:157", "Rablerinin mağfiret ve rahmeti onlaradır. O'nun yolunda olanlar da onlardır."),
        ("Bakara 2:163", "Tanrınız bir tek Tanrıdır. O, merhamet eden, merhametli olandan başka Tanrı yoktur."),
        ("Bakara 2:172", "Ey İnananlar! Sizi rızıklandırdığımızın temizlerinden yiyin; yalnız Allah'a kulluk ediyorsanız, O'na şükredin."),
        ("Bakara 2:207", "İnsanlar arasında, Allah'ın rızasını kazanmak için canını verenler vardır. Allah kullarına karşı şefkatlidir."),
        ("Bakara 2:218", "İnananlar, hicret edenler ve Allah yolunda cihad edenler Allah'ın rahmetini umarlar. Allah bağışlar ve merhamet eder."),
        ("Bakara 2:238", "Namazlara ve orta namaza devam edin; gönülden boyun eğerek Allah için namaza durun."),
        ("Bakara 2:263", "Güzel bir söz ve bağışlama, peşinden eza gelen bir sadakadan daha iyidir. Allah müstağnidir, Halim'dir."),
        ("Bakara 2:270", "Sarfettiğiniz harcı ve adadığınız adağı şüphesiz Allah bilir. Zulmedenlerin hiç yardımcıları yoktur."),
        ("Bakara 2:280", "Borçlu darda ise, eli genişleyinceye kadar ona mühlet verin. Bilmiş olsanız borcu bağışlamanız sizin için daha hayırlıdır."),
        ("Âl-i İmrân 3:9", "Rabbimiz! Doğrusu geleceği şüphe götürmeyen günde, insanları toplayacak olan Sensin. Şüphesiz ki Allah verdiği sözden caymaz."),
        ("Âl-i İmrân 3:31", "De ki: \"Allah'ı seviyorsanız bana uyun. Allah da sizi sevsin ve günahlarınızı bağışlasın. Allah affeder ve merhamet eder\"."),
        ("Âl-i İmrân 3:38", "Orada Zekeriya Rabbine dua etti: \"Ya Rabbi! Bana kendi katından temiz bir soy bahşet, doğrusu Sen duayı işitirsin\"."),
        ("Âl-i İmrân 3:53", "\"Rabbimiz! İndirdiğine inandık, Peygambere uyduk; bizi sahid olanlarla beraber yaz\"."),
        ("Âl-i İmrân 3:68", "Doğrusu İbrahim'e en yakın olanlar, ona uyanlar, bu Peygamber ve inananlardır. Allah inananların dostudur."),
        ("Âl-i İmrân 3:74", "\"Rahmetini dilediğine tahsis eder, Allah büyük, bol nimet sahibidir\"."),
        ("Âl-i İmrân 3:76", "Hayır, öyle değil; ahdini yerine getiren ve günahtan sakınan bilsin ki, Allah sakınanları şüphesiz sever."),
        ("Âl-i İmrân 3:107", "Yüzleri ağaranlar ise Allah'ın rahmetindedirler. Onlar orada temellidirler."),
        ("Âl-i İmrân 3:115", "Ne iyilik yaparlarsa, karşılığını bulacaklardır. Allah sakınanları bilir."),
        ("Âl-i İmrân 3:122", "Sizden iki takım bozulup geri çekilmek üzere idi; oysa Allah onların dostu idi, inananlar yalnız Allah'a güvensinler."),
        ("Âl-i İmrân 3:123", "And olsun ki, siz düşkün bir durumda iken, Bedir'de, Allah size yardım etmişti; Allah'tan sakının ki şükredebilesiniz."),
        ("Âl-i İmrân 3:132", "Size merhamet edilmesi için, Allah'a ve Peygamber'e itaat edin."),
        ("Âl-i İmrân 3:133", "Rabbinizin mağfiretine ve Allah'a karşı gelmekten sakınanlar için hazırlanmış eni gökler ve yer kadar olan cennete koşuşun."),
        ("Âl-i İmrân 3:148", "Bu yüzden Allah onlara dünya nimetini de ahiret nimetini de fazlasiyle verdi. Allah işlerini iyi yapanları sever."),
        ("Âl-i İmrân 3:150", "Halbuki Mevlanız Allah'tır. O, yardımcıların en iyisidir."),
        ("Âl-i İmrân 3:194", "\"Rabbimiz! Peygamberlerinle vadettiklerini bize ver, kıyamet günü bizi rezil etme. Sen şüphesiz sözünden caymazsın\"."),
        ("Nisâ 4:4", "Kadınlara mehirlerini cömertçe verin, eğer ondan gönül hoşluğu ile size bir şey bağışlarlarsa onu afiyetle yiyin."),
        ("Nisâ 4:8", "Taksimde, yakınlar, yetimler ve düşkünler bulunursa, ondan onlara da verin, güzel sözler söyleyin."),
        ("Nisâ 4:40", "Allah şüphesiz zerre kadar haksızlık yapmaz, zerre kadar iyilik olsa onu kat kat arttırır ve yapana büyük ecir verir."),
        ("Nisâ 4:45", "Allah, düşmanlarınızı çok iyi bilir. Allah size dost olarak da yeter, yardımcı olarak da yeter."),
        ("Nisâ 4:70", "Bu nimet, Allah'tandır. Bilen olarak Allah yeter."),
        ("Nisâ 4:99", "İşte Allah'ın bunları affetmesi umulur. Allah Affedendir, Bağışlayan'dır."),
        ("Nisâ 4:106", "Allah'tan mağfiret dile. Allah bağışlar ve merhamet eder."),
        ("Nisâ 4:124", "Erkek veya kadın, mümin olarak, kim yararlı işler işlerse, işte onlar cennete girerler, kendilerine zerre kadar zulmedilmez."),
        ("Nisâ 4:130", "Ayrılırlarsa, Allah her birini nimetinin genişliğiyle yoksulluktan kurtarır, Allah her şeyi kaplayandır. Hakim'dir."),
        ("Nisâ 4:134", "Dünya nimetini kim isterse, bilsin ki, dünyanın ve ahiretin nimeti Allah'ın katındadır. Allah işitir ve görür."),
        ("Mâide 5:9", "Allah, inananlara ve yararlı işler işleyenlere mağfiret ve büyük ecir olduğunu vadetmiştir."),
        ("Mâide 5:55", "Sizin dostunuz ancak Allah, O'nun Peygamberi ve namaz kılan, zekat veren ve rüku eden müminlerdir."),
        ("Mâide 5:74", "Allah'a tevbe etmezler, O'ndan mağfiret dilemezler mi? Oysa Allah Bağışlayan'dır, merhamet edendir."),
        ("Mâide 5:111", "Havarilere, \"Bana ve peygamberime inanın\" diye bildirmiştim, \"İnandık, bizim müslimler olduğumuza şahid ol\" demişlerdi."),
        ("En'âm 6:67", "Her haberin gerçekleşeceği bir zaman vardır ki siz onu yakında bileceksiniz."),
        ("En'âm 6:82", "İşte güven; onlara, inanıp haksızlık karıştırmayanlaradır. Onlar doğru yoldadırlar."),
        ("En'âm 6:162", "De ki: \"Namazım, ibadetlerim, hayatım ve ölümüm, alemlerin Rabbi Allah içindir."),
        ("A'râf 7:10", "Sizi yeryüzünde yerleştirdik ve orada size geçimlikler yarattık. Öyleyken pek az şükrediyorsunuz."),
        ("A'râf 7:23", "Her ikisi, \"Rabbimiz! Kendimize yazık ettik; bizi bağışlamaz ve bize merhamet etmezsen biz kaybedenlerden oluruz\" dediler."),
        ("A'râf 7:72", "Biz, rahmetimizle, Hud'u ve beraberinde bulunanları kurtardık, ayetlerimizi yalan sayarak inanmayanların kökünü kestik."),
        ("A'râf 7:144", "\"Ey Musa! Verdiklerimle ve seninle konuşmamla seni insanlar arasından seçtim; sana verdiğimi al ve şükret\" dedi."),
        ("A'râf 7:151", "Musa \"Rabbim! Beni ve kardeşimi bağışla, bize acı, Sen merhametlilerin merhametlisisin\" dedi."),
        ("A'râf 7:154", "Musa, öfkesi yatışınca, bir nüshasında Rablerinden korkanlar için doğru yol ve rahmet yazılı olan levhaları aldı."),
        ("A'râf 7:192", "Oysa putlar ne onlara yardım edebilir ve ne de kendilerine bir yardımları olur."),
        ("A'râf 7:199", "Sen af yolunu tut, bağışla, uygun olanı emret, bilgisizlere aldırış etme."),
        ("A'râf 7:204", "Kuran okunduğu zaman ona kulak verin, dinleyin ki merhamet olunasınız."),
        ("Enfâl 8:9", "Rabbinizin yardımına sığınıyordunuz. O, \"Ben size, birbiri peşinden bin melekle yardım ederim\" diye cevap vermişti."),
        ("Enfâl 8:23", "Allah onlarda bir iyilik görseydi onlara işittirirdi. Onlara işittirmiş olsaydı yine de yüz çevirirlerdi, zaten dönektirler."),
        ("Enfâl 8:27", "Ey inananlar! Allah'a ve Peygambere karşı hainlik etmeyin, size güvenilen şeylere bile bile hıyanet etmiş olursunuz."),
        ("Enfâl 8:45", "Ey inananlar! Bir toplulukla karşılaşırsanız dayanın; başarıya erişebilmeniz için Allah'ı çok anın."),
        ("Enfâl 8:64", "Allah'ın yardımı sana ve sana uyan müminlere yeter."),
        ("Enfâl 8:69", "Elde ettiğiniz ganimetleri temiz ve helal olarak yiyin; Allah'tan sakının, doğrusu Allah bağışlar ve merhamet eder."),
        ("Tevbe 9:27", "Allah bundan sonra da dilediğinin tevbesini kabul eder. Allah bağışlar ve merhamet eder."),
        ("Tevbe 9:76", "Allah onlara bol nimetinden verince, cimrilik ettiler, yüz çevirdiler. Zaten dönektirler."),
        ("Tevbe 9:89", "Allah onlara temelli kalacakları, içlerinden ırmaklar akan cennetler hazırlamıştır. Büyük kurtuluş budur."),
        ("Tevbe 9:114", "İbrahim'in, babası için mağfiret dilemesi, sadece ona verdiği bir sözden ötürü idi."),
        ("Yûnus 10:25", "Allah, cennete çağırır ve dilediğini doğru yola eriştirir."),
        ("Yûnus 10:57", "Ey insanlar! Rabbinizden size bir öğüt ve kalblerde olana şifa, inananlara doğruyu gösteren bir rehber ve rahmet gelmiştir."),
        ("Yûnus 10:58", "De ki: \"Bunlar, Allah'ın bol nimeti ve rahmetiyledir.\" Buna sevinsinler. O, onların topladıklarından daha hayırlıdır."),
        ("Yûnus 10:64", "Dünya hayatında da, ahirette de müjde onlaradır. Allah'ın sözlerinde hiçbir değişme yoktur. Bu büyük başarıdır."),
        ("Yûnus 10:77", "Musa: \"Size gelen gerçeğe dil mi uzatırsınız? Bu sihir midir? Sihirbazlar zaten başarı kazanamazlar\" dedi."),
        ("Yûnus 10:84", "Musa: \"Ey milletim! Allah'a inanıyorsanız ve teslim olmuşsanız O'na güvenin\" dedi."),
        ("Yûnus 10:89", "Allah: \"İkinizin duası kabul olundu. Dürüst hareket edin; bilmeyenlerin yoluna asla uymayın\" dedi."),
        ("Yûnus 10:109", "Sana vahyedilene uy; Allah hükmünü verene kadar sabret. O, hüküm verenlerin en iyisidir."),
        ("Hûd 11:9", "And olsun ki, insana nimetimizi tattırır sonra onu ondan çekip alırsak, o şüphesiz umutsuz bir nanköre döner."),
        ("Hûd 11:11", "Bunların dışında, sabredip iyi işler işleyen kimseler, işte onlara mağfiret ve büyük ecir vardır."),
        ("Hûd 11:23", "Doğrusu inanan ve yararlı iş yapanlar ve Rablerine boyun eğenler, işte onlar cennetliklerdir; orada temellidirler."),
        ("Hûd 11:41", "Allah \"Oraya binin; yürümesi ve durması Allah'ın ismiyledir, Rabbin bağışlar ve merhamet eder\" dedi."),
        ("Hûd 11:71", "Bu arada, İbrahim'in ayakta duran karısı gülünce, \"Ona İshak'ı ardından Yakub'u müjdeleriz\" dediler."),
        ("Hûd 11:74", "İbrahim'in korkusu gidip de müjde kendisine ulaşınca, Lut milleti hakkında elçilerimizle tartışmaya girişti."),
        ("Hûd 11:95", "Sanki orada hiç yaşamamışlardı. Bilin ki Semud milleti Allah'ın rahmetinden uzaklaştığı gibi Medyen halkı da uzaklaştı."),
        ("Hûd 11:115", "Sabret, Allah iyi davrananların ecrini elbette zayi etmez."),
        ("Yûsuf 12:34", "Rabbi onun duasını kabul etti ve kadınların tuzağına engel oldu. Zira O, işitir ve bilir."),
        ("Yûsuf 12:58", "Yusuf'un kardeşleri gelip yanına girdiler. Kendisini tanımadıkları halde o onları tanıdı."),
        ("Yûsuf 12:69", "Yusuf'un yanına girdiklerinde, kardeşini bağrına bastı ve: \"Ben senin kardeşinim, onların yaptıklarına artık üzülme\" dedi."),
        ("Yûsuf 12:97", "Oğulları: \"Ey Babamız! Suçlarımızın bağışlanmasını dile, bizler hiç şüphesiz suçluyuz\" dediler."),
        ("Yûsuf 12:98", "Yakub: \"Rabbim'den bağışlanmanızı dileyeceğim; O şüphesiz bağışlar ve merhamet eder\" dedi."),
        ("Yûsuf 12:99", "Yusuf'un yanına geldiklerinde, o, anasını babasını bağrına bastı, \"Allah'ın dileğince, güven içinde Mısır'da yerleşin\" dedi."),
        ("İbrâhîm 14:15", "Peygamberler yardım istediler ve her inatçı zorba hüsrana uğradı."),
        ("Hicr 15:4", "Yok ettiğimiz herhangi bir kasabanın elbette belli bir yazısı vardır."),
        ("Hicr 15:45", "Allah'a karşı gelmekten sakınanlar ise, cennetlerde, pınar başlarındadırlar."),
        ("Hicr 15:46", "\"Oraya güven içinde, esenlikle girin\" denilir."),
        ("Hicr 15:55", "\"Seni gerçekten müjdeliyoruz, umutsuzlardan olma\" demişlerdi."),
        ("Hicr 15:61", "Elçiler Lut'un ailesine gelince, Lut: \"Doğrusu siz tanınmayan kimselersiniz\" dedi."),
        ("Hicr 15:62", "Elçiler Lut'un ailesine gelince, Lut: \"Doğrusu siz tanınmayan kimselersiniz\" dedi."),
        ("Hicr 15:82", "Dağlarda, güven içinde olarak evler yontuyorlardı."),
        ("Nahl 16:7", "Kendi kendinize zor varacağınız memleketlere, yüklerinizi taşırlar. Doğrusu Rabbiniz şefkatlidir, merhametlidir."),
        ("Nahl 16:18", "Allah'ın verdiği nimetleri sayacak olsanız bitiremezsiniz; doğrusu Allah bağışlar, merhamet eder."),
        ("Nahl 16:32", "Melekler onların canını temizlenmiş olarak alırken: \"Selam size; yaptıklarınıza karşılık haydi cennete girin\" derler."),
        ("Nahl 16:53", "Size gelen her nimet Allah'tandır. Sonra, bir sıkıntıya uğradığınızda yalnız O'na sığınırsınız."),
        ("Nahl 16:58", "Aralarından birine bir kızı olduğu müjdelendiği zaman içi gamla dolarak yüzü simsiyah kesilir."),
        ("Nahl 16:114", "Yalnız Allah'a kulluk ediyorsanız, Allah'ın size helal ve temiz olarak verdiği rızıklardan yiyin, O'nun nimetine şükredin."),
        ("Nahl 16:121", "Rabbinin nimetlerine şükrederdi; Rabbi de onu seçti ve doğru yola eriştirdi."),
        ("Nahl 16:122", "Dünyada ona güzellik verdik, ahirette de o mutlaka barışsever iyiler arasında yer alacaktır."),
        ("Nahl 16:127", "Sabret, senin sabrın ancak Allah'ın yardımıyladır; onlara üzülme, kurdukları düzenlerden de endişe etme."),
        ("Nahl 16:128", "Allah şüphesiz sakınanlarla ve iyilik yapanlarla beraberdir."),
        ("İsrâ 17:13", "Her insanın boynuna işlediklerini dolarız ve kıyamet günü açılmış bulacağı Kitap'ı önüne çıkarırız."),
        ("İsrâ 17:19", "Ahireti isteyip, inanmış olarak onun için gerekli çalışmada bulunan kimselerin, işte onların çalışmaları şükre değer."),
        ("İsrâ 17:25", "İçinizde olanı en iyi Rabbiniz bilir. İyi kimselerseniz bilin ki O şüphesiz, Kendine baş vuranları bağışlar."),
        ("İsrâ 17:26", "Yakınına, düşküne, yolcuya hakkını ver; elindekileri saçıp savurma."),
        ("İsrâ 17:66", "Rabbiniz, bol nimetinden elde edesiniz diye, denizde gemileri sizin için yüzdürür. O, size merhamet eder."),
        ("İsrâ 17:79", "Geceleyin uyanıp, yalnız sana mahsus olarak fazladan namaz kıl. Belki de Rabbin seni övülecek makama yükseltir."),
        ("İsrâ 17:87", "Bunu yapmayışı ancak Rabbinin sana merhamet etmesindendir. Çünkü O'nun sana olan nimeti büyüktür."),
        ("İsrâ 17:105", "Kuran'ı ancak hak olarak indirdik ve o da indiği gibi hak olarak kaldı. Seni de yalnız müjdeci ve uyarıcı olarak gönderdik."),
        ("Kehf 18:10", "Birkaç genç mağaraya sığınmış: \"Rabbimiz! Katından bize rahmet ver ve işimizde doğruyu göster, bizi başarılı kıl\" demişlerdi."),
        ("Kehf 18:43", "Ona, Allah'tan başka yardım edebilecek adamları da yoktu, kendi kendini de kurtaramadı."),
        ("Kehf 18:54", "And olsun ki, Biz bu Kuran'da insanlara türlü türlü misali gösterip açıkladık. İnsanın en çok yaptığı iş tartışmadır."),
        ("Kehf 18:62", "Oradan uzaklaştıklarında Musa, yanındaki gence: \"Azığımızı çıkar, and olsun bu yolculuğumuzda yorgun düştük\" dedi."),
        ("Kehf 18:65", "Bu arada ikisi katımızdan kendisine bir rahmet verdiğimiz ve kendisine ilim öğrettiğimiz kullarımızdan birini buldular."),
        ("Kehf 18:67", "O: \"Sen doğrusu benim yaptıklarıma dayanamazsın, bilgice kavrayamadığın bir şeye nasıl dayanabilirsin?\" dedi."),
        ("Kehf 18:68", "Musa: \"İnşallah sabrettiğimi göreceksin, sana hiçbir işte baş kaldırmayacağım\" dedi."),
        ("Kehf 18:72", "Musa'ya: \"Ben sana yaptığım işlere dayanamazsın demedim mi?\" dedi."),
        ("Kehf 18:75", "O: \"Ben sana, yaptığım işlere dayanamazsın demedim mi?\" dedi."),
        ("Kehf 18:107", "Ama inanıp yararlı iş işleyenlerin konakları Firdevs cennetleridir."),
        ("Meryem 19:2", "Bu, Rabbinin kulu Zekeriya'ya olan rahmetini anmadır."),
        ("Meryem 19:7", "Allah: \"Ey Zekeriya! Sana, Yahya isminde bir oğlanı müjdeliyoruz. Bu adı daha önce kimseye vermemiştik\" buyurdu."),
        ("Meryem 19:19", "Cebrail: \"Ben temiz bir oğlan bağışlamak için Rabbinin sana gönderdiği elçiden başkası değilim\" dedi."),
        ("Meryem 19:52", "Ona Tur'un sağ yanından seslenmiş ve konuşmak için onu yaklaştırmıştık."),
        ("Meryem 19:53", "Rahmetimizden, kardeşi Harun'u bir peygamber olarak ona bağışladık."),
        ("Meryem 19:55", "Çevresinde bulunanlara namaz kılmalarını, zekat vermelerini emrederdi. Rabbinin katında hoşnutluğa ermişti."),
        ("Meryem 19:56", "Kitap'da İdris'i de zikret, çünkü o dosdoğru bir peygamberdi."),
        ("Meryem 19:63", "Kullarımızdan Allah'a karşı gelmekten sakınanları mirasçı kılacağımız Cennet işte budur."),
        ("Tâhâ 20:15", "Herkes işlediğinin karşılığını görsün diye, zamanını gizli tuttuğum kıyamet mutlaka gelecektir."),
        ("Tâhâ 20:50", "Musa: \"Rabbimiz, her şeye ayrı bir özellik veren, sonra doğru yola eriştirendir\" dedi."),
        ("Tâhâ 20:82", "Doğrusu Ben, tevbe edeni, inanıp yararlı iş işleyerek doğru yola gireni bağışlarım."),
        ("Enbiyâ 21:13", "\"Koşup kaçmayın; size nimet verilen yere, yurdlarınıza dönün, elbette sorguya çekileceksiniz\" dedik."),
        ("Enbiyâ 21:75", "Lut'u rahmetimizin içine aldık; doğrusu o iyilerdendi."),
        ("Enbiyâ 21:76", "Nuh da daha önceleri Bize yalvarmıştı, onun duasını kabul edip, kendisini ve ailesini büyük sıkıntıdan kurtardık."),
        ("Enbiyâ 21:83", "Eyyub da: \"Başıma bir bela geldi, (Sana sığındım), Sen merhametlilerin merhametlisisin\" diye Rabbine nida etmişti."),
        ("Enbiyâ 21:85", "İsmail, İdris ve Zülkifl hakkında anlattığımızı da an; onların her biri sabredenlerdendi."),
        ("Enbiyâ 21:107", "Biz seni ancak alemlere rahmet olarak gönderdik."),
        ("Enbiyâ 21:112", "Peygamber: \"Rabbim! Aramızda gerçekle hükmet, anlattıklarınıza karşı ancak Rahman olan Rabbimizden yardım istenir\" dedi."),
        ("Hac 22:50", "Cömertçe verilmiş rızık ve mağfiret, inanan ve yararlı iş işleyenleredir."),
        ("Hac 22:56", "İşte o gün hükümranlık Allah'ındır. O aralarında hükmeder. İnanıp yararlı iş işleyenler nimet cennetlerindedirler."),
        ("Hac 22:77", "Ey inananlar! Rüku edin, secdeye varın, Rabbiniz'e kulluk edin, iyilik yapın ki saadete erişesiniz."),
        ("Mü'minûn 23:10", "İşte onlar, temelli kalacakları Firdevs cennetine varis olanlardır."),
        ("Mü'minûn 23:11", "İşte onlar, temelli kalacakları Firdevs cennetine varis olanlardır."),
        ("Mü'minûn 23:39", "O peygamber: \"Rabbim! Beni yalancı saymalarına karşılık bana yardım et\" dedi."),
        ("Mü'minûn 23:41", "Gerçekten, onları bir çığlık yakaladı ve onları süprüntü yığını haline getirdik. Haksızlık eden millet, rahmetden ırak olsun!"),
        ("Mü'minûn 23:55", "Kendilerine mal ve oğullar vermekle, iyiliklerde onlar için acele ettiğimizi mi zannederler? Hayır; farkında değiller."),
        ("Mü'minûn 23:56", "Kendilerine mal ve oğullar vermekle, iyiliklerde onlar için acele ettiğimizi mi zannederler? Hayır; farkında değiller."),
        ("Mü'minûn 23:78", "Oysa, sizin için kulaklar, gözler ve kalbler vareden O'dur. Pek az şükrediyorsunuz."),
        ("Mü'minûn 23:79", "Sizi yerde yaratıp yayan O'dur ve O'nun huzurunda toplanacaksınız."),
        ("Mü'minûn 23:101", "Sura üflendiği zaman, o gün, aralarındaki soy yakınlığı fayda vermez ve birbirlerine de birşey soramazlar."),
        ("Nûr 24:5", "Ama bundan sonra, tevbe edip düzelenler bunun dışındadır. Şüphesiz Allah bağışlar ve merhamet eder."),
        ("Nûr 24:20", "Allah'ın size lütuf ve merhameti bulunmasaydı, Allah şefkatli ve merhametli olmasaydı hemen cezanızı verirdi."),
        ("Nûr 24:56", "Namaz kılın, zekat verin, Peygambere itaat edin ki size merhamet edilsin."),
        ("Furkân 25:4", "İnkar edenler: \"Bu Kuran uydurmadır, ona başka bir topluluk yardım etmiştir\" diyerek haksız ve asılsız bir söz uydurdular."),
        ("Furkân 25:16", "Temelli kalacakları cennette diledikleri şeyleri bulurlar. Bu, Rabbinin yerine getirilmesi istenen bir vaadidir."),
        ("Furkân 25:24", "O gün, cennetliklerin kalacağı yer çok iyi, dinlenecekleri yer çok güzeldir."),
        ("Furkân 25:31", "Her peygamber için, böylece suçlulardan bir düşman ortaya koyarız. Doğruyu gösterici ve yardımcı olarak, Rabbin yeter."),
        ("Furkân 25:33", "Sana bir misal vermezler ki, Biz onun gerçeğini ve en iyi anlaşılanını sana vermemiş olalım."),
        ("Furkân 25:56", "Biz seni sadece müjdeci ve uyarıcı olarak gönderdik."),
        ("Furkân 25:58", "Ölümsüz, diri olan Allah'a güven, O'nu överek tesbih et. Kullarının günahlarından haberdar olarak kendisi yeter."),
        ("Furkân 25:62", "İbret almak veya şükretmek dileyen kimseler için gece ile gündüzü birbiri ardınca getiren O'dur."),
        ("Şuarâ 26:9", "Rabbin şüphesiz güçlüdür, merhametlidir."),
        ("Şuarâ 26:25", "Yanında bulunanlara: \"İşitmiyor musunuz?\" dedi."),
        ("Şuarâ 26:68", "Doğrusu Rabbin, güçlü olandır, merhamet edendir."),
        ("Şuarâ 26:104", "Rabbin şüphesiz güçlüdür, merhametlidir."),
        ("Şuarâ 26:122", "Rabbin şüphesiz güçlüdür, merhametlidir."),
        ("Şuarâ 26:159", "Rabbin şüphesiz güçlüdür, merhametlidir."),
        ("Şuarâ 26:191", "Rabbin şüphesiz güçlüdür, merhametlidir."),
        ("Şuarâ 26:196", "O, daha öncekilerin kitabında da zikredilmiştir."),
        ("Şuarâ 26:217", "Senin kalkıp namaz kılanlar arasında bulunduğunu gören, güçlü ve merhametli olan Allah'a güven. Doğrusu O işitir ve bilir."),
        ("Şuarâ 26:218", "Senin kalkıp namaz kılanlar arasında bulunduğunu gören, güçlü ve merhametli olan Allah'a güven. Doğrusu O işitir ve bilir."),
        ("Şuarâ 26:219", "Senin kalkıp namaz kılanlar arasında bulunduğunu gören, güçlü ve merhametli olan Allah'a güven. Doğrusu O işitir ve bilir."),
        ("Şuarâ 26:220", "Senin kalkıp namaz kılanlar arasında bulunduğunu gören, güçlü ve merhametli olan Allah'a güven. Doğrusu O işitir ve bilir."),
        ("Neml 27:2", "Bunlar, namaz kılan, zekat veren ve ahirete de kesin olarak inanan müminlere doğruluk rehberi ve müjdedir."),
        ("Neml 27:3", "Bunlar, namaz kılan, zekat veren ve ahirete de kesin olarak inanan müminlere doğruluk rehberi ve müjdedir."),
        ("Neml 27:39", "Cinlerden bir ifrit: \"Sen yerinden kalkmadan önce sana onu getiririm, buna karşı güvenilir bir güce sahibim\" dedi."),
        ("Neml 27:73", "Doğrusu Rabbin, insanlara karşı lütuf sahibidir. Fakat onların çoğu şükretmezler."),
        ("Neml 27:77", "Doğrusu Kuran, inananlara doğruluk rehberi ve rahmettir."),
        ("Neml 27:79", "Allah'a güven, şüphesiz sen apaçık gerçek üzerindesin."),
        ("Neml 27:89", "Kim bir iyilik getirirse, ona daha iyisi verilir. Onlar o günün korkusundan güvendedirler."),
        ("Kasas 28:17", "Musa: \"Rabbim! Bana verdiğin nimete and olsun ki, suçlulara asla yardımcı olmayacağım\" dedi."),
        ("Kasas 28:26", "İki kadından biri: \"Babacığım! Onu ücretli olarak tut; ücretle tuttuklarının en iyisi bu güçlü ve güvenilir adamdır\" dedi."),
        ("Ankebût 29:30", "Lut: \"Rabbim! Bozgunculara karşı bana yardım et\" dedi."),
        ("Ankebût 29:51", "Kendilerine okunan bir Kitap'ı sana indirmiş olmamız onlara yetmiyor mu? Bunda, inanan topluluk için rahmet ve ibret vardır."),
        ("Ankebût 29:56", "Ey inanmış kullarım! Benim yarattığım yeryüzü geniştir. O halde güven içinde olacağınız yere gidip yalnız Bana kulluk ediniz."),
        ("Rûm 30:15", "Ama inanıp yararlı iş işleyenler, ağırlanacakları bir cennette bulunurlar."),
        ("Rûm 30:60", "Sabret ki, Allah'ın sözü şüphesiz gerçektir. Kesin olarak inanmayanlar seni hafife almasınlar."),
        ("Lokmân 31:2", "Bunlar, iyi davranan kimseler için rahmet ve doğru yol rehberi olan hikmetli Kitap'ın ayetleridir."),
        ("Lokmân 31:3", "Bunlar, iyi davranan kimseler için rahmet ve doğru yol rehberi olan hikmetli Kitap'ın ayetleridir."),
        ("Lokmân 31:4", "O kimseler namazı kılarlar, zekatı verirler; ahirete de yakinen inanırlar."),
        ("Secde 32:6", "O, görülmeyeni de görüleni de bilendir, güçlüdür, merhametlidir."),
        ("Secde 32:17", "Yaptıklarına karşılık onlar için saklanan müjdeyi kimse bilmez."),
        ("Secde 32:19", "İnanıp yararlı iş işleyenlere gelince, onların yaptıklarına karşılık, varacakları cennet konakları vardır."),
        ("Secde 32:24", "Sabredip ayetlerimize kesin olarak inanmalarından ötürü, aralarından, onları buyruğumuzla doğru yola götüren önderler yaptık."),
        ("Ahzâb 33:3", "Allah'a güven, Allah, vekil olarak yeter."),
        ("Ahzâb 33:43", "Karanlıklardan aydınlığa çıkarmak için size rahmet ve istiğfar eden Allah ve melekleridir. İnananlara merhamet eden O'dur."),
        ("Ahzâb 33:45", "Biz seni şahit, müjdeci, uyarıcı; Allah'ın izniyle O'na çağıran, nurlandıran bir ışık olarak göndermişizdir."),
        ("Ahzâb 33:46", "Biz seni şahit, müjdeci, uyarıcı; Allah'ın izniyle O'na çağıran, nurlandıran bir ışık olarak göndermişizdir."),
        ("Ahzâb 33:47", "İnananlara, Rablerinden büyük bir lütuf olduğunu müjdele."),
        ("Ahzâb 33:48", "İnkarcılara, ikiyüzlülere itaat etme; eziyetlerine aldırma; Allah'a güven, güvenilecek olarak Allah yeter."),
        ("Sebe' 34:2", "Yere gireni ve oradan çıkanı, gökten ineni ve oraya yükseleni bilir. O, merhametlidir, mağfiret sahibidir."),
        ("Sebe' 34:28", "Biz seni bütün insanlara ancak müjdeci ve uyarıcı olarak göndermişizdir; fakat insanların çoğu bilmez."),
        ("Fâtır 35:33", "Bunlar, Adn cennetlerine girerler. Orada altın bilezikler ve incilerle süslenirler, oradaki elbiseleri de ipektir."),
        ("Yâsîn 36:5", "Bu, babaları uyarılmadığından gafil kalmış bir milleti uyarman için güçlü ve merhametli olan Allah'ın indirdiği Kuran'dır."),
        ("Yâsîn 36:6", "Bu, babaları uyarılmadığından gafil kalmış bir milleti uyarman için güçlü ve merhametli olan Allah'ın indirdiği Kuran'dır."),
        ("Yâsîn 36:16", "Elçiler: \"Doğrusu Rabbimiz bizim size gönderildiğimizi bilir; bize düşen ancak apaçık tebliğdir\" demişlerdi."),
        ("Yâsîn 36:17", "Elçiler: \"Doğrusu Rabbimiz bizim size gönderildiğimizi bilir; bize düşen ancak apaçık tebliğdir\" demişlerdi."),
        ("Yâsîn 36:43", "Dilesek, onları suda boğardık; ne yardımlarına koşan bulunur ve ne de kendileri kurtulabilirlerdi."),
        ("Yâsîn 36:44", "Ama katımızdan bir rahmet ve bir süreye kadar geçinme olarak onları geri bıraktık."),
        ("Yâsîn 36:53", "Tek bir çığlık kopar, hepsi, hemen huzurumuza getirilmiş olur."),
        ("Yâsîn 36:55", "Doğrusu bugün, cennetlikler eğlenceyle meşguldürler."),
        ("Yâsîn 36:58", "Merhametli olan Rab katından onlara selam vardır."),
        ("Yâsîn 36:74", "Allah'ı bırakıp da, kendilerine yardımı dokunur diye, başka tanrılar edindiler."),
        ("Yâsîn 36:75", "Oysa onlar yardım edemezler, ancak kendileri o tanrılara koruyuculuk için nöbet beklerler."),
        ("Sâffât 37:6", "Şüphesiz Biz, yakın göğü bir süsle, yıldızlarla süsledik."),
        ("Sâffât 37:41", "İşte bildirilen rızık ve meyveler onlaradır. Nimet cennetlerinde, karşılıklı tahtlar üzerinde kendilerine ikram olunur."),
        ("Sâffât 37:42", "İşte bildirilen rızık ve meyveler onlaradır. Nimet cennetlerinde, karşılıklı tahtlar üzerinde kendilerine ikram olunur."),
        ("Sâffât 37:43", "İşte bildirilen rızık ve meyveler onlaradır. Nimet cennetlerinde, karşılıklı tahtlar üzerinde kendilerine ikram olunur."),
        ("Sâffât 37:44", "İşte bildirilen rızık ve meyveler onlaradır. Nimet cennetlerinde, karşılıklı tahtlar üzerinde kendilerine ikram olunur."),
        ("Sâffât 37:54", "Yanındakilere: \"Siz onu bilir misiniz?\" der."),
        ("Sâffât 37:75", "And olsun ki, Nuh Bize seslenmişti de duasına ne güzel icabet etmiştik."),
        ("Sâffât 37:101", "Biz de ona yumuşak huylu bir oğlan müjdeledik."),
        ("Sâffât 37:112", "Ona, iyilerden olan İshak'ı peygamber olarak müjdeledik."),
        ("Sâffât 37:114", "And olsun ki Musa ve Harun'a da iyilikte bulunmuştuk."),
        ("Sâd 38:25", "Böylece onu bağışlamıştık. Katımızda onun yakınlığı ve güzel bir geleceği vardır."),
        ("Sâd 38:40", "Doğrusu onun katımızda yakınlığı ve güzel bir istikbali vardır."),
        ("Sâd 38:50", "Kapıları onlara açılmış Adn cennetleri vardır."),
        ("Zümer 39:31", "Ey insanlar! Sonra siz, kıyamet günü Rabbinizin huzurunda duruşmaya çıkacaksınız."),
        ("Mü'min 40:51", "Doğrusu Biz, peygamberlerimize ve inananlara dünya hayatında ve şahidlerin şahidlik edecekleri günde yardım ederiz."),
        ("Mü'min 40:55", "Sabret, Allah'ın verdiği söz şüphesiz gerçektir. Suçunun bağışlanmasını dile; Rabbini akşam, sabah, överek tesbih et."),
        ("Fussilet 41:35", "Bu, ancak sabredenlere vergidir; bu ancak o büyük hazzı tadanlara vergidir."),
        ("Şûrâ 42:17", "Gerçekten Kitap'ı ve ölçüyü indiren Allah'tır. Ne bilirsin, belki de kıyamet saati yakındır."),
        ("Şûrâ 42:28", "Umutsuzluğa düşmelerinin ardından yağmuru indiren, rahmetini yayan O'dur. O, övülmeğe layık olan dosttur."),
        ("Şûrâ 42:30", "Başınıza gelen herhangi bir musibet ellerinizle işlediklerinizden ötürüdür. O, yine de çoğunu affeder."),
        ("Şûrâ 42:31", "Yeryüzünde O'nu aciz bırakamazsınız. Allah'tan başka bir dostunuz da yardımcınız da yoktur."),
        ("Şûrâ 42:39", "Bir haksızlığa uğradıklarında, üstün gelmek için aralarında yardımlaşırlar."),
        ("Şûrâ 42:43", "Ama sabredip bağışlayanın işi, işte bu, azmedilmeye değer işlerdendir."),
        ("Zuhruf 43:59", "Meryemoğlu, ancak kendisine nimet verdiğimiz ve İsrailoğullarına örnek kıldığımız bir kuldur."),
        ("Zuhruf 43:72", "İşlediklerinize karşılık, size miras verilen işte bu cennettir."),
        ("Duhân 44:22", "Bunlar, suçlu bir millet olduğu için, Rabbine yardım etmesi için yalvardı."),
        ("Duhân 44:25", "Orada nice bahçeler, pınarlar, ekinler, güzel konaklar, eğlenip durdukları nimetler bırakmışlardı."),
        ("Duhân 44:26", "Orada nice bahçeler, pınarlar, ekinler, güzel konaklar, eğlenip durdukları nimetler bırakmışlardı."),
        ("Duhân 44:27", "Orada nice bahçeler, pınarlar, ekinler, güzel konaklar, eğlenip durdukları nimetler bırakmışlardı."),
        ("Duhân 44:41", "O gün, dostun dosta hiçbir faydası olmaz, yardım da görmezler."),
        ("Duhân 44:42", "Yalnız, Allah'ın merhamet ettiği kimseler bunların dışındadır. O, şüphesiz güçlüdür, merhametlidir."),
        ("Duhân 44:51", "Allah'a karşı gelmekten sakınmış olanlar ise, güvenli bir yerde, bahçelerde ve pınar başlarındadırlar."),
        ("Duhân 44:52", "Allah'a karşı gelmekten sakınmış olanlar ise, güvenli bir yerde, bahçelerde ve pınar başlarındadırlar."),
        ("Duhân 44:55", "Orada, güven içinde olarak her yemişi isteyebilirler."),
        ("Câsiye 45:20", "Bu Kuran, insanlar için açık belgeler; kesin olarak inanan millet için doğruluk rehberi ve rahmettir."),
        ("Câsiye 45:30", "İnanıp, yararlı iş işleyenlere gelince, Rableri onları rahmetine garkeder. İşte bu, apaçık kurtuluştur."),
        ("Ahkâf 46:13", "Doğrusu, \"Rabbimiz Allah'tır\" deyip, sonra da dosdoğru gidenlere korku yoktur, onlar üzülmeyeceklerdir."),
        ("Ahkâf 46:14", "İşte onlar, cennetliklerdir; işlediklerine karşılık olarak, içinde temelli kalacaklardır."),
        ("Muhammed 47:13", "Seni sürüp çıkaran şehirden daha kuvvetli olan nice şehirler yok ettik. Yardım edenleri bulunmadı."),
        ("Muhammed 47:31", "And olsun ki sizi, içinizden cihada çıkanları ve sabredenleri meydana çıkarana ve haberlerinizi açıklayana kadar deneyeceğiz."),
        ("Fetih 48:2", "Allah böylece, senin geçmiş ve gelecek günahlarını bağışlar, sana olan nimetini tamamlar, seni doğru yola eriştirir."),
        ("Fetih 48:3", "Böylece sana, kimsenin güç yetiremeyeceği bir şekilde yardım eder."),
        ("Kâf 50:16", "And olsun ki insanı Biz yarattık; nefsinin kendisine fısıldadıklarını biliriz; Biz ona şah damarından daha yakınız."),
        ("Kâf 50:17", "Sağında ve solunda, onunla beraber oturan iki alıcı melek, yanında hazır birer gözcü olarak söylediği her sözü zaptederler."),
        ("Kâf 50:18", "Sağında ve solunda, onunla beraber oturan iki alıcı melek, yanında hazır birer gözcü olarak söylediği her sözü zaptederler."),
        ("Kâf 50:23", "Yanındaki melek: \"İşte bu yanımdaki hazırdır\" der."),
        ("Kâf 50:31", "Cennet, Allah'a karşı gelmekten sakınanlara yaklaştırılır, zaten uzakta değildir."),
        ("Kâf 50:39", "Söylediklerine sabret; Rabbini, güneşin doğmasından önce ve batışından önce överek tesbih et."),
        ("Kâf 50:41", "Bir çağırıcının yakın bir yerden çağıracağı güne kulak ver."),
        ("Zâriyât 51:12", "İşlerin karşılık göreceği günün zamanını sorarlar."),
        ("Zâriyât 51:18", "Seher vakitlerinde bağışlanma dilerlerdi."),
        ("Zâriyât 51:28", "(Yemediklerini görünce) onlardan endişeye düştü; \"Korkma\" dediler ve ona bilgin bir oğul sahibi olacağını müjdelediler."),
        ("Zâriyât 51:45", "Ayağa kalkacak güçleri kalmadı, yardım da görmediler."),
        ("Tûr 52:22", "Cennette olanlara diledikleri meyve ve etten bol bol veririz."),
        ("Tûr 52:29", "Öğüt ver; Rabbinin nimetiyle sen, ne kahinsin ne de delisin."),
        ("Tûr 52:46", "O gün, düzenleri kendilerine bir fayda vermez; yardım da görmezler."),
        ("Necm 53:9", "Araları iki yay aralığı kadar veya daha da yakın oldu."),
        ("Kamer 54:10", "O da: \"Ben yenildim, bana yardım et\" diye Rabbine yalvarmıştı."),
        ("Rahmân 55:41", "Suçlular simalarından tanınırlar da, alın saçlarından ve ayaklarından yakalanırlar."),
        ("Rahmân 55:46", "Rabbine karşı durmaktan korkan kimseye iki cennet vardır."),
        ("Rahmân 55:52", "Bu cennetlerde türlü meyveden çift çift vardır."),
        ("Rahmân 55:54", "Orada, örtüleri parlak atlastan yataklara yaslanırlar; iki cennetin meyvelerini de kolayca toplarlar."),
        ("Rahmân 55:62", "Bu iki cennetten başka iki cennet daha vardır."),
        ("Rahmân 55:76", "Cennetlikler orada yeşil yastıklara ve harikulade işlemeli döşeklere yaslanırlar."),
        ("Vâkıa 56:11", "Naim cennetlerinde Allah'a en çok yaklaştırılmış olanlar işte bunlardır."),
        ("Vâkıa 56:12", "Naim cennetlerinde Allah'a en çok yaklaştırılmış olanlar işte bunlardır."),
        ("Vâkıa 56:42", "İnsanın içine işleyen bir sıcaklık ve kaynar su içinde, serinliği ve hoşluğu olmayan kara bir dumanın gölgesinde bulunurlar."),
        ("Vâkıa 56:43", "İnsanın içine işleyen bir sıcaklık ve kaynar su içinde, serinliği ve hoşluğu olmayan kara bir dumanın gölgesinde bulunurlar."),
        ("Vâkıa 56:44", "İnsanın içine işleyen bir sıcaklık ve kaynar su içinde, serinliği ve hoşluğu olmayan kara bir dumanın gölgesinde bulunurlar."),
        ("Vâkıa 56:45", "Çünkü onlar, bundan önce, dünyada, nimet içinde bulunurlar iken, büyük günah işlemekte direnir dururlardı."),
        ("Vâkıa 56:46", "Çünkü onlar, bundan önce, dünyada, nimet içinde bulunurlar iken, büyük günah işlemekte direnir dururlardı."),
        ("Vâkıa 56:83", "Kişinin canı boğaza dayanınca ve siz o zaman bakıp kalırken, Biz o kişiye sizden daha yakınızdır, ama görmezsiniz."),
        ("Vâkıa 56:84", "Kişinin canı boğaza dayanınca ve siz o zaman bakıp kalırken, Biz o kişiye sizden daha yakınızdır, ama görmezsiniz."),
        ("Vâkıa 56:85", "Kişinin canı boğaza dayanınca ve siz o zaman bakıp kalırken, Biz o kişiye sizden daha yakınızdır, ama görmezsiniz."),
        ("Saff 61:4", "Doğrusu Allah, kendi uğrunda, kenetlenmiş bir duvar gibi, saf halinde çarpışanları sever."),
        ("Saff 61:13", "Bundan başka, sevdiğiniz bir şey daha: Allah katından bir yardım ve yakın bir zafer vardır. İnananlara müjde ver."),
        ("Cum'a 62:10", "Namaz bitince yeryüzüne yayılın; Allah'ın lütfundan rızık isteyin; Allah'ı çok anın ki saadete erişesiniz."),
        ("Münâfikûn 63:11", "Bir canın eceli gelip çatınca, Allah onu asla geri bırakmaz; Allah, işlediklerinizden haberdardır."),
    ]
}
