// OTOMATİK ÜRETİLDİ – tools/generate_widget_verses.py
// Kaynak: assets/database/quran.db (Türkçe meal)
// Kilit ekranında asla kesilmeyecek (<= 85 karakter) zengin ve duygusal ayet havuzu

struct WidgetVerseData {
    static let all: [(ref: String, text: String)] = [
        ("İnşirâh 94:6", "Şüphesiz her güçlükle beraber bir kolaylık vardır."),
        ("Duhâ 93:3", "Rabbin seni terk etmedi ve sana darılmadı."),
        ("Duhâ 93:5", "Rabbin sana verecek ve sen razı olacaksın."),
        ("Ra'd 13:28", "Bilin ki, kalpler ancak Allah'ı anmakla huzur bulur."),
        ("Yûsuf 12:86", "Ben hüzün ve kederimi ancak Allah'a arz ederim."),
        ("Bakara 2:186", "Kullarım Beni sorarlarsa, şüphesiz Ben onlara çok yakınım."),
        ("Bakara 2:152", "Beni anın ki Ben de sizi anayım; Bana şükredin."),
        ("Bakara 2:153", "Ey iman edenler! Sabır ve namazla yardım dileyin."),
        ("Zümer 39:36", "Allah kuluna kâfi değil midir?"),
        ("Zümer 39:53", "Allah'ın rahmetinden ümidinizi kesmeyin."),
        ("Tevbe 9:40", "Üzülme, çünkü Allah bizimle beraberdir."),
        ("Tâhâ 20:46", "Korkmayın, şüphesiz Ben sizinle beraberim; işitir ve görürüm."),
        ("Tâhâ 20:25-26", "Rabbim! Gönlüme ferahlık ver, işimi bana kolaylaştır."),
        ("Talâk 65:3", "Kim Allah'a tevekkül ederse, O kendisine yeter."),
        ("Mü'min 40:60", "Rabbiniz buyurdu ki: Bana dua edin, size icabet edeyim."),
        ("Hûd 11:90", "Şüphesiz Rabbim merhametlidir, çok sevendir."),
        ("Âl-i İmrân 3:139", "Gevşemeyin, üzülmeyin; inanmışsanız üstün sizsiniz."),
        ("Yûnus 10:62", "İyi bilin ki, Allah'ın dostlarına asla korku ve hüzün yoktur."),
        ("Hûd 11:115", "Sabret; Allah güzel davrananların mükâfatını zayi etmez."),
        ("Nisâ 4:132", "Göklerde ve yerde ne varsa Allah'ındır. Vekil olarak O yeter."),
        ("A'râf 7:55", "Rabbinize gönülden ve gizlice yalvarın."),
        ("Kâf 50:16", "Biz insana şah damarından daha yakınız."),
        ("Âl-i İmrân 3:173", "Allah bize yeter; O ne güzel vekildir."),
        ("İbrâhîm 14:39", "Şüphesiz Rabbim duayı hakkıyla işitendir."),
        ("Bakara 2:286", "Allah hiçbir kimseye gücünün yettiğinden fazlasını yüklemez."),
        ("A'râf 7:56", "Şüphesiz Allah'ın rahmeti iyilik edenlere pek yakındır."),
        ("İsrâ 17:24", "Rabbim! Onlar beni küçükken koruduğu gibi Sen de merhamet et."),
        ("Kehf 18:10", "Rabbimiz! Bize katından bir rahmet ver ve işimizde kolaylık lütfet."),
        ("Şûrâ 42:25", "O, kullarının tövbesini kabul eden, günahları bağışlayandır."),
        ("Âl-i İmrân 3:159", "Şüphesiz Allah, tevekkül edenleri sever."),
        ("Âl-i İmrân 3:146", "Allah sabredenleri sever."),
        ("İbrâhîm 14:40", "Rabbim! Beni ve neslimi namazı dosdoğru kılanlardan eyle."),
        ("Tahrîm 66:8", "Rabbimiz! Nurumuzu tamamla ve bizi bağışla."),
        ("Bakara 2:257", "Allah inananların dostudur; onları karanlıklardan nura çıkarır."),
        ("Fussilet 41:34", "Kötülüğü en güzel olanla sav; düşmanın sımsıcak bir dost oluverir."),
        ("Kalem 68:4", "Şüphesiz sen pek yüce bir ahlak üzerindesin."),
        ("Bakara 2:43", "Namazı kılın, zekatı verin, rüku edenlerle birlikte rüku edin."),
        ("Bakara 2:152", "Artık Beni anın, Ben de sizi anayım; Bana şükredin, nankörlük etmeyin."),
        ("Bakara 2:157", "Rablerinin mağfiret ve rahmeti onlaradır. O'nun yolunda olanlar da onlardır."),
        ("Bakara 2:163", "Tanrınız bir tek Tanrıdır. O, merhamet eden, merhametli olandan başka Tanrı yoktur."),
        ("Bakara 2:238", "Namazlara ve orta namaza devam edin; gönülden boyun eğerek Allah için namaza durun."),
        ("Âl-i İmrân 3:53", "\"Rabbimiz! İndirdiğine inandık, Peygambere uyduk; bizi sahid olanlarla beraber yaz\"."),
        ("Âl-i İmrân 3:74", "\"Rahmetini dilediğine tahsis eder, Allah büyük, bol nimet sahibidir\"."),
        ("Âl-i İmrân 3:107", "Yüzleri ağaranlar ise Allah'ın rahmetindedirler. Onlar orada temellidirler."),
        ("Âl-i İmrân 3:115", "Ne iyilik yaparlarsa, karşılığını bulacaklardır. Allah sakınanları bilir."),
        ("Âl-i İmrân 3:132", "Size merhamet edilmesi için, Allah'a ve Peygamber'e itaat edin."),
        ("Âl-i İmrân 3:139", "Gevşemeyin, üzülmeyin, inanmışsanız, mutlaka siz en üstünsünüzdür."),
        ("Âl-i İmrân 3:150", "Halbuki Mevlanız Allah'tır. O, yardımcıların en iyisidir."),
        ("Nisâ 4:70", "Bu nimet, Allah'tandır. Bilen olarak Allah yeter."),
        ("Nisâ 4:99", "İşte Allah'ın bunları affetmesi umulur. Allah Affedendir, Bağışlayan'dır."),
        ("Nisâ 4:106", "Allah'tan mağfiret dile. Allah bağışlar ve merhamet eder."),
        ("En'âm 6:67", "Her haberin gerçekleşeceği bir zaman vardır ki siz onu yakında bileceksiniz."),
        ("En'âm 6:82", "İşte güven; onlara, inanıp haksızlık karıştırmayanlaradır. Onlar doğru yoldadırlar."),
        ("En'âm 6:162", "De ki: \"Namazım, ibadetlerim, hayatım ve ölümüm, alemlerin Rabbi Allah içindir."),
        ("A'râf 7:55", "Rabbinize gönülden ve gizlice yalvarın. Doğrusu O aşırı gidenleri sevmez."),
        ("A'râf 7:192", "Oysa putlar ne onlara yardım edebilir ve ne de kendilerine bir yardımları olur."),
        ("A'râf 7:199", "Sen af yolunu tut, bağışla, uygun olanı emret, bilgisizlere aldırış etme."),
        ("A'râf 7:204", "Kuran okunduğu zaman ona kulak verin, dinleyin ki merhamet olunasınız."),
        ("Enfâl 8:64", "Allah'ın yardımı sana ve sana uyan müminlere yeter."),
        ("Tevbe 9:114", "İbrahim'in, babası için mağfiret dilemesi, sadece ona verdiği bir sözden ötürü idi."),
        ("Yûnus 10:25", "Allah, cennete çağırır ve dilediğini doğru yola eriştirir."),
        ("Yûnus 10:62", "İyi bilin ki, Allah'ın dostlarına korku yoktur, onlar üzülmeyeceklerdir."),
        ("Yûnus 10:84", "Musa: \"Ey milletim! Allah'a inanıyorsanız ve teslim olmuşsanız O'na güvenin\" dedi."),
        ("Hûd 11:115", "Sabret, Allah iyi davrananların ecrini elbette zayi etmez."),
        ("İbrâhîm 14:15", "Peygamberler yardım istediler ve her inatçı zorba hüsrana uğradı."),
        ("Hicr 15:4", "Yok ettiğimiz herhangi bir kasabanın elbette belli bir yazısı vardır."),
        ("Hicr 15:45", "Allah'a karşı gelmekten sakınanlar ise, cennetlerde, pınar başlarındadırlar."),
        ("Hicr 15:46", "\"Oraya güven içinde, esenlikle girin\" denilir."),
        ("Hicr 15:55", "\"Seni gerçekten müjdeliyoruz, umutsuzlardan olma\" demişlerdi."),
        ("Hicr 15:61", "Elçiler Lut'un ailesine gelince, Lut: \"Doğrusu siz tanınmayan kimselersiniz\" dedi."),
        ("Hicr 15:82", "Dağlarda, güven içinde olarak evler yontuyorlardı."),
        ("Nahl 16:121", "Rabbinin nimetlerine şükrederdi; Rabbi de onu seçti ve doğru yola eriştirdi."),
        ("Nahl 16:128", "Allah şüphesiz sakınanlarla ve iyilik yapanlarla beraberdir."),
        ("İsrâ 17:26", "Yakınına, düşküne, yolcuya hakkını ver; elindekileri saçıp savurma."),
        ("İsrâ 17:109", "Ağlayarak yüz üstü yere kapanırlar; bu, onların gönüllerindeki saygıyı artırır."),
        ("Kehf 18:68", "Musa: \"İnşallah sabrettiğimi göreceksin, sana hiçbir işte baş kaldırmayacağım\" dedi."),
        ("Kehf 18:72", "Musa'ya: \"Ben sana yaptığım işlere dayanamazsın demedim mi?\" dedi."),
        ("Kehf 18:75", "O: \"Ben sana, yaptığım işlere dayanamazsın demedim mi?\" dedi."),
        ("Kehf 18:107", "Ama inanıp yararlı iş işleyenlerin konakları Firdevs cennetleridir."),
        ("Meryem 19:2", "Bu, Rabbinin kulu Zekeriya'ya olan rahmetini anmadır."),
        ("Meryem 19:52", "Ona Tur'un sağ yanından seslenmiş ve konuşmak için onu yaklaştırmıştık."),
        ("Meryem 19:53", "Rahmetimizden, kardeşi Harun'u bir peygamber olarak ona bağışladık."),
        ("Meryem 19:56", "Kitap'da İdris'i de zikret, çünkü o dosdoğru bir peygamberdi."),
        ("Tâhâ 20:68", "\"Korkma, sen muhakkak daha üstünsün\" dedik."),
        ("Tâhâ 20:82", "Doğrusu Ben, tevbe edeni, inanıp yararlı iş işleyerek doğru yola gireni bağışlarım."),
        ("Enbiyâ 21:75", "Lut'u rahmetimizin içine aldık; doğrusu o iyilerdendi."),
        ("Enbiyâ 21:107", "Biz seni ancak alemlere rahmet olarak gönderdik."),
        ("Hac 22:50", "Cömertçe verilmiş rızık ve mağfiret, inanan ve yararlı iş işleyenleredir."),
        ("Mü'minûn 23:9", "Namazlarına riayet ederler."),
        ("Mü'minûn 23:10", "İşte onlar, temelli kalacakları Firdevs cennetine varis olanlardır."),
        ("Mü'minûn 23:39", "O peygamber: \"Rabbim! Beni yalancı saymalarına karşılık bana yardım et\" dedi."),
        ("Mü'minûn 23:78", "Oysa, sizin için kulaklar, gözler ve kalbler vareden O'dur. Pek az şükrediyorsunuz."),
        ("Mü'minûn 23:79", "Sizi yerde yaratıp yayan O'dur ve O'nun huzurunda toplanacaksınız."),
        ("Nûr 24:56", "Namaz kılın, zekat verin, Peygambere itaat edin ki size merhamet edilsin."),
        ("Furkân 25:24", "O gün, cennetliklerin kalacağı yer çok iyi, dinlenecekleri yer çok güzeldir."),
        ("Furkân 25:30", "Peygamber: \"Ey Rabbim! Doğrusu milletim bu Kuran'ı terketmişti\" der."),
        ("Furkân 25:56", "Biz seni sadece müjdeci ve uyarıcı olarak gönderdik."),
        ("Şuarâ 26:9", "Rabbin şüphesiz güçlüdür, merhametlidir."),
        ("Şuarâ 26:25", "Yanında bulunanlara: \"İşitmiyor musunuz?\" dedi."),
        ("Şuarâ 26:68", "Doğrusu Rabbin, güçlü olandır, merhamet edendir."),
        ("Şuarâ 26:140", "Doğrusu Rabbin güçlüdür, merhametlidir."),
        ("Şuarâ 26:196", "O, daha öncekilerin kitabında da zikredilmiştir."),
        ("Şuarâ 26:214", "Önce en yakın hısımlarını uyar."),
        ("Neml 27:73", "Doğrusu Rabbin, insanlara karşı lütuf sahibidir. Fakat onların çoğu şükretmezler."),
        ("Neml 27:74", "Şüphesiz Rabbin onların gönüllerinin gizlediklerini de, açığa vurduklarını da bilir."),
        ("Neml 27:77", "Doğrusu Kuran, inananlara doğruluk rehberi ve rahmettir."),
        ("Neml 27:79", "Allah'a güven, şüphesiz sen apaçık gerçek üzerindesin."),
        ("Kasas 28:69", "Rabbin gönüllerinin gizlediklerini ve açığa vurduklarını bilir."),
        ("Ankebût 29:30", "Lut: \"Rabbim! Bozgunculara karşı bana yardım et\" dedi."),
        ("Rûm 30:15", "Ama inanıp yararlı iş işleyenler, ağırlanacakları bir cennette bulunurlar."),
        ("Lokmân 31:4", "O kimseler namazı kılarlar, zekatı verirler; ahirete de yakinen inanırlar."),
        ("Secde 32:6", "O, görülmeyeni de görüleni de bilendir, güçlüdür, merhametlidir."),
        ("Secde 32:17", "Yaptıklarına karşılık onlar için saklanan müjdeyi kimse bilmez."),
        ("Ahzâb 33:3", "Allah'a güven, Allah, vekil olarak yeter."),
        ("Ahzâb 33:41", "Ey inananlar! Allah'ı çok anın."),
        ("Ahzâb 33:47", "İnananlara, Rablerinden büyük bir lütuf olduğunu müjdele."),
        ("Fâtır 35:16", "Dilerse sizi yokeder, yeniden başkalarını yaratır."),
        ("Fâtır 35:38", "Allah şüphesiz, göklerin ve yerin gaybını bilir. Doğrusu O kalplerde olanı bilendir."),
        ("Yâsîn 36:32", "Hepsi huzurumuza getirileceklerdir."),
        ("Yâsîn 36:44", "Ama katımızdan bir rahmet ve bir süreye kadar geçinme olarak onları geri bıraktık."),
        ("Yâsîn 36:53", "Tek bir çığlık kopar, hepsi, hemen huzurumuza getirilmiş olur."),
        ("Yâsîn 36:55", "Doğrusu bugün, cennetlikler eğlenceyle meşguldürler."),
        ("Yâsîn 36:58", "Merhametli olan Rab katından onlara selam vardır."),
        ("Yâsîn 36:74", "Allah'ı bırakıp da, kendilerine yardımı dokunur diye, başka tanrılar edindiler."),
        ("Sâffât 37:6", "Şüphesiz Biz, yakın göğü bir süsle, yıldızlarla süsledik."),
        ("Sâffât 37:54", "Yanındakilere: \"Siz onu bilir misiniz?\" der."),
        ("Sâffât 37:75", "And olsun ki, Nuh Bize seslenmişti de duasına ne güzel icabet etmiştik."),
        ("Sâffât 37:84", "Nitekim Rabbine temiz bir kalple geldi."),
        ("Sâffât 37:101", "Biz de ona yumuşak huylu bir oğlan müjdeledik."),
        ("Sâffât 37:112", "Ona, iyilerden olan İshak'ı peygamber olarak müjdeledik."),
        ("Sâffât 37:114", "And olsun ki Musa ve Harun'a da iyilikte bulunmuştuk."),
        ("Sâd 38:25", "Böylece onu bağışlamıştık. Katımızda onun yakınlığı ve güzel bir geleceği vardır."),
        ("Sâd 38:40", "Doğrusu onun katımızda yakınlığı ve güzel bir istikbali vardır."),
        ("Sâd 38:50", "Kapıları onlara açılmış Adn cennetleri vardır."),
        ("Zümer 39:31", "Ey insanlar! Sonra siz, kıyamet günü Rabbinizin huzurunda duruşmaya çıkacaksınız."),
        ("Mü'min 40:19", "Allah gözlerin hainliğini ve gönüllerin gizlediğini bilir."),
        ("Fussilet 41:35", "Bu, ancak sabredenlere vergidir; bu ancak o büyük hazzı tadanlara vergidir."),
        ("Şûrâ 42:39", "Bir haksızlığa uğradıklarında, üstün gelmek için aralarında yardımlaşırlar."),
        ("Şûrâ 42:43", "Ama sabredip bağışlayanın işi, işte bu, azmedilmeye değer işlerdendir."),
        ("Zuhruf 43:68", "Allah: \"Ey kullarım! Bugün size korku yoktur, siz üzülmeyeceksiniz\" der."),
        ("Zuhruf 43:72", "İşlediklerinize karşılık, size miras verilen işte bu cennettir."),
        ("Duhân 44:22", "Bunlar, suçlu bir millet olduğu için, Rabbine yardım etmesi için yalvardı."),
        ("Duhân 44:41", "O gün, dostun dosta hiçbir faydası olmaz, yardım da görmezler."),
        ("Duhân 44:55", "Orada, güven içinde olarak her yemişi isteyebilirler."),
        ("Fetih 48:3", "Böylece sana, kimsenin güç yetiremeyeceği bir şekilde yardım eder."),
        ("Kâf 50:23", "Yanındaki melek: \"İşte bu yanımdaki hazırdır\" der."),
        ("Kâf 50:31", "Cennet, Allah'a karşı gelmekten sakınanlara yaklaştırılır, zaten uzakta değildir."),
        ("Kâf 50:41", "Bir çağırıcının yakın bir yerden çağıracağı güne kulak ver."),
        ("Zâriyât 51:12", "İşlerin karşılık göreceği günün zamanını sorarlar."),
        ("Zâriyât 51:18", "Seher vakitlerinde bağışlanma dilerlerdi."),
        ("Zâriyât 51:45", "Ayağa kalkacak güçleri kalmadı, yardım da görmediler."),
        ("Tûr 52:22", "Cennette olanlara diledikleri meyve ve etten bol bol veririz."),
        ("Tûr 52:29", "Öğüt ver; Rabbinin nimetiyle sen, ne kahinsin ne de delisin."),
        ("Tûr 52:46", "O gün, düzenleri kendilerine bir fayda vermez; yardım da görmezler."),
        ("Necm 53:9", "Araları iki yay aralığı kadar veya daha da yakın oldu."),
        ("Necm 53:15", "Orada Me'va cenneti vardır."),
        ("Kamer 54:10", "O da: \"Ben yenildim, bana yardım et\" diye Rabbine yalvarmıştı."),
        ("Rahmân 55:41", "Suçlular simalarından tanınırlar da, alın saçlarından ve ayaklarından yakalanırlar."),
        ("Rahmân 55:46", "Rabbine karşı durmaktan korkan kimseye iki cennet vardır."),
        ("Rahmân 55:48", "Bu iki cennet türlü ağaçlarla doludur."),
        ("Rahmân 55:50", "Bu cennetlerden akan iki kaynak vardır."),
        ("Rahmân 55:52", "Bu cennetlerde türlü meyveden çift çift vardır."),
        ("Rahmân 55:62", "Bu iki cennetten başka iki cennet daha vardır."),
        ("Rahmân 55:76", "Cennetlikler orada yeşil yastıklara ve harikulade işlemeli döşeklere yaslanırlar."),
        ("Vâkıa 56:11", "Naim cennetlerinde Allah'a en çok yaklaştırılmış olanlar işte bunlardır."),
        ("Teğâbün 64:13", "Allah vardır, O'ndan başka tanrı yoktur. İnananlar yalnız Allah 'a güvensinler."),
        ("Kalem 68:5", "Hanginizin aklından zoru olduğunu yakında sen de göreceksin, onlar da görecekler."),
        ("Kalem 68:16", "Onun havada olan burnunu yakında yere sürteceğiz."),
        ("Kalem 68:25", "Yoksullara yardım etmeye güçleri yeterken böyle konuşarak erkenden gittiler."),
        ("Kalem 68:29", "\"Rabbimizi tenzih ederiz; doğrusu biz yazık etmiştik\" dediler."),
        ("Kalem 68:34", "Allah'a karşı gelmekten sakınanlara, Rableri katında nimet cennetleri vardır."),
        ("Kalem 68:49", "Rabbinin katından ona bir nimet ulaşmasaydı, kınanmış olarak sahile atılacaktı."),
        ("Hâkka 69:18", "O gün siz huzura alınırsınız, hiçbir şeyiniz gizli kalmaz."),
        ("Meâric 70:7", "Ama biz onu yakın görmekteyiz."),
        ("Meâric 70:35", "İşte onlar, cennetlerde ikram olunacak kimselerdir."),
        ("Müddessir 74:53", "Hayır; daha doğrusu ahiretten korkmazlar."),
        ("Kıyâme 75:12", "O gün, sen, Rabbinin huzuruna varıp durursun."),
        ("Kıyâme 75:20", "Hayır, hayır! Sizler, çabuk elde edeceğiniz dünya nimetlerini seversiniz."),
        ("Kıyâme 75:30", "O gün sevk Rabbin huzurunadır."),
        ("İnsân 76:3", "Şüphesiz ona yol gösterdik; buna kimi şükreder, kimi de nankörlük."),
        ("İnsân 76:12", "Sabırlarının karşılığı, cennet ve oradaki ipeklerdir."),
        ("İnsân 76:20", "Oranın neresine baksan, nimet ve büyük bir saltanat görürsün."),
        ("İnsân 76:22", "\"İşte bu sizin işlediklerinizin karşılığıdır, çalışmalarınız şükre değer\" denir."),
        ("Abese 80:1", "Yanına kör bir kimse geldi diye (Peygamber) yüzünü asıp çevirdi."),
        ("Abese 80:17", "Canı çıksın o insanın, o ne nankördür!"),
        ("İnfitâr 82:13", "İyiler şüphesiz nimet içindedirler."),
        ("Mutaffifîn 83:6", "O gün insanlar Alemlerin Rabbinin huzurunda dururlar."),
        ("Mutaffifîn 83:22", "İyiler, şüphesiz, nimet içinde ve tahtlar üzerinde etrafı seyrederler."),
        ("İnşikâk 84:13", "Çünkü o, dünyada, adamlarının yanında iken zevk içindeydi."),
        ("Bürûc 85:14", "Yüce arşın sahibi, çok seven, bağışlayan O'dur."),
        ("Târık 86:10", "O gün, insanın gücü de, yardımcısı da olmaz."),
        ("A'lâ 87:14", "Arınmış olan, Rabbinin adını anıp namaz kılan, saadete erişecektir."),
        ("Ğâşiye 88:10", "Yüksek bir cennettedirler."),
        ("Fecr 89:27", "Ey huzur içinde olan can!"),
        ("Duhâ 93:3", "Rabbin seni ne bıraktı ve ne de sana darıldı."),
        ("Duhâ 93:11", "Yalnızca Rabbinin nimetini anlat."),
        ("İnşirâh 94:5", "Elbette güçlükle beraber şüphesiz bir kolaylık vardır."),
        ("İnşirâh 94:6", "Gerçekten, güçlükle beraber bir kolaylık vardır."),
        ("Zilzâl 99:7", "Kim zerre kadar iyilik yapmışsa onu görür."),
        ("Tekâsür 102:3", "Hayır; öyle olmayın; yakında bileceksiniz."),
        ("Tekâsür 102:4", "Hayır; gözünüzü açın; yakında bileceksiniz."),
        ("Kevser 108:1", "Doğrusu sana pek çok nimet vermişizdir."),
        ("Kevser 108:2", "Öyleyse Rabbin için namaz kıl, kurban kes."),
    ]
}
